# Created with YamlCreate.ps1 v2.2.12 $debug=NVS1.CRLF.5-1-19041-3693.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: CMB.PB
PackageVersion: 7.7.5
InstallerType: exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://dl.cmbimg.com/download/PB/PBSetup775.exe
  InstallerSha256: 10122FC34EC04A9E887304AF4B5581771AD77D8A6BA522E55D8C6F799CFA5A24
ManifestType: installer
ManifestVersion: 1.5.0
