# Created with YamlCreate.ps1 v2.2.12 $debug=NVS1.CRLF.5-1-19041-3693.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: KingstVIS.KingstVIS
PackageVersion: 3.6.4
PackageLocale: en-US
Publisher: KingstVIS
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: KingstVIS
# PackageUrl: 
License: Proprietary
# LicenseUrl: 
# Copyright: 
# CopyrightUrl: 
ShortDescription: KingstVIS
# Description: 
# Moniker: 
# Tags: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
# PurchaseUrl: 
# InstallationNotes: 
# Documentations: 
ManifestType: defaultLocale
ManifestVersion: 1.5.0
