# Created with YamlCreate.ps1 v2.2.12 $debug=NVS0.CRLF.5-1-19041-3693.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Nvidia.cudnn
PackageVersion: 9.1.0.70
PackageLocale: en-US
Publisher: Nvidia
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: Nvidia cudnn
# PackageUrl: 
License: Proprietary
# LicenseUrl: 
# Copyright: 
# CopyrightUrl: 
ShortDescription: cudnn
# Description: 
Moniker: cudnn
# Tags: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
# PurchaseUrl: 
# InstallationNotes: 
# Documentations: 
ManifestType: defaultLocale
ManifestVersion: 1.5.0
