# Created with YamlCreate.ps1 v2.2.12 $debug=NVS0.CRLF.5-1-19041-3693.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.5.0.schema.json

PackageIdentifier: Nvidia.cudnn
PackageVersion: 9.1.0.70
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.5.0
